export { default as Add } from './Add'
export { default as Check } from './Check'
export { default as Cross } from './Cross'
export { default as Edit } from './Edit'
export { default as RecFilled } from './RecFilled'
export { default as RecOutlined } from './RecOutlined'
